- hosts: localhost
  connection: local
  roles:
    - { role: common }
    - { role: ubuntu }
    - {
        when: ansible_os_family == 'Archlinux',
        role: archlinux,
        chruby_version: v0.3.9,
        rubies_location: /opt/rubies/,
        ruby_version: 2.5.3
      }
