---
- stat: 
    path: "{{rubies_location}}/ruby-{{ruby_version}}"
  register: ruby_version_present

- name: Ruby | Install ruby_version if necessary
  command: 'ruby-install ruby {{ruby_version}}'
  when: ruby_version_present.stat.exists == False
  become: yes
