---
- name: install vim
  pacman:
    name: gvim
  become: yes
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '~/.vim'
    - '~/.vim/bundle'
- name: Clone ctrlp plugin
  git:  repo=https://github.com/kien/ctrlp.vim.git
    dest=~/.vim/bundle/ctrlp.vim
- name: Clone vim-buffergator plugin
  git:  repo=https://github.com/jeetsukumaran/vim-buffergator.git
    dest=~/.vim/bundle/vim-buffergator.vim

- name: Clone vim-ruby plugin
  git:  repo=https://github.com/vim-ruby/vim-ruby.git
    dest=~/.vim/bundle/vim-ruby.vim

- name: Clone nerdtree plugin
  git:  repo=https://github.com/scrooloose/nerdtree.git
    dest=~/.vim/bundle/nerdtree.vim

- name: Clone fugitive plugin
  git:  repo=https://github.com/tpope/vim-fugitive.git
    dest=~/.vim/bundle/vim-fugitive.vim

- name: Clone tpope/vim-surround plugin
  git:  repo=https://tpope.io/vim/surround.git
    dest=~/.vim/bundle/vim-surround.vim

- name: Configure my ~/.vimrc
  copy:
    dest: ~/.vimrc
    content: |
      scriptencoding utf-8
      set encoding=utf-8
      let mapleader=','

      set background=dark

      set runtimepath^=~/.vim/bundle/nerdtree.vim
      map <C-f> :NERDTreeToggle<CR>
      let g:NERDTreeDirArrowExpandable='|'
      let g:NERDTreeDirArrowCollapsible='+'

      set runtimepath^=~/.vim/bundle/vim-surround.vim
      set runtimepath^=~/.vim/bundle/ctrlp.vim

      " Configure vim-ruby
      set runtimepath^=~/.vim/bundle/vim-ruby.vim
      set nocompatible      " We're running Vim, not Vi!
      syntax on             " Enable syntax highlighting
      filetype on           " Enable filetype detection
      filetype indent on    " Enable filetype-specific indenting
      filetype plugin on    " Enable filetype-specific plugins

      set runtimepath^=~/.vim/bundle/vim-buffergator.vim
      let g:buffergator_viewport_split_policy = "B"
      let g:buffergator_display_regime = "bufname"

      set runtimepath^=~/.vim/bundle/vim-fugitive.vim

      " Move to alternatefile, faster nem control+6
      nnoremap <space><space> <c-^>

      " Fix common typos like :Q or :W
      " (https://github.com/leafac/dotfiles/blob/master/vim/files/config/general/mappings.vim)
      command! -bang -nargs=* -complete=file E e<bang> <args>
      command! -bang -nargs=* -complete=file W w<bang> <args>
      command! -bang -nargs=* -complete=file Wq wq<bang> <args>
      command! -bang -nargs=* -complete=file WQ wq<bang> <args>
      command! -bang Wa wa<bang>
      command! -bang WA wa<bang>
      command! -bang Q q<bang>
      command! -bang QA qa<bang>
      command! -bang Qa qa<bang>

      " Show invisible chars
      set list
      set listchars=tab:»\ ,trail:·

      " Remove trailling whitespace before saving
      autocmd BufWritePre * :%s/\s\+$//e

      " Autoindent
      set autoindent

      " Turn on smartindentation
      set smartindent

      " Default spaces
      set ts=2 sts=2 sw=2 expandtab

      " Spaces for filetypes
      autocmd FileType makefile setlocal sts=4 sts=4 sw=4 noexpandtab
      autocmd FileType markdown setlocal sts=4 sts=4 sw=4 expandtab
      autocmd FileType python   setlocal sts=4 sts=4 sw=4 expandtab
      autocmd FileType php      setlocal sts=4 sts=4 sw=4 expandtab

      " Load indent file for the current filetype
      filetype indent on " Enable filetype-specific indenting
      filetype plugin on " Enable filetype-specific plugins


      " After a yank keep in the end of selection
      vnoremap y ygv<esc>

      " Copy and paste to system clipboard
      set clipboard=unnamedplus

      " Toggle paste mode
      set pastetoggle=<leader>p

      " Make pasting in visual-mode sane, by not replacing the register content with
      " the erased one
      vnoremap p pgvy

      " Y act like C and D. Yank from the cursor to the end of the line,
      " (https://github.com/leafac/dotfiles/blob/master/vim/files/config/general/mappings.vim)
      nnoremap Y y$

      "-------------------------temp-files
      " Backup is always nice
      set backup

      " Undo available even after buffer close
      set undofile

      " Maximum number of changes that can be undone
      set undolevels=1000

      " Maximum number lines to save for undo on a buffer reload
      set undoreload=10000

      " Create those directories if they don't exist already
      silent execute '!mkdir -p ~/.vim/{backup_files,swap_files,undo_files}'

      set backupdir=~/.vim/backup_files//
      set directory=~/.vim/swap_files//
      set undodir=~/.vim/undo_files//

      "------------screen

      " Switch syntax highlighting on, when the terminal has colors
      " Also switch on highlighting the last used search pattern.
      if (&t_Co > 2 || has("gui_running")) && !exists("syntax_on")
      syntax on
      endif

      " GUI font
      set guifont=Monaco:h16

      " Turn syntax on
      syntax enable

      " Show line numbers
      set nu rnu

      " Encoding should be utf-8
      set encoding=utf-8

      " Scroll should happen before cursor reaches end of the screen
      set scrolloff=3

      " Show partial commands while being typed
      set showcmd

      " Buffers should be hidden when I left them, and I don't want Vim
      " complaining about it!
      set hidden

      " Enhanced tab completion on command insert
      set wildmenu
      set wildmode=list:longest

      " Improve redrawing
      set ttyfast

      " Show cursor position on last line
      set ruler

      " Backspace over anything
      set backspace=indent,eol,start

      " Always show status
      set laststatus=2

      " Show invisible chars
      set list
      set listchars=tab:»\ ,trail:·

      " Show ruler on column 80
      set colorcolumn=80
