- name: Configure my ~/.bashrc
  copy:
    dest: /home/alface/.bashrc
    content: |
        function git_dirty {
        	st=$(git status 2>/dev/null | tail -n 1)
        	if [[ $st != "nothing to commit (working directory clean)" ]]
        	then
        		echo "*"
        	fi
        }
        function color_my_prompt {
        	local __user_and_host="\[\033[01;32m\]\u@\h"
        	local __cur_location="\[\033[01;34m\]\w"
        	local __git_branch_color="\[\033[31m\]"
        	local __git_branch='`git branch 2> /dev/null | grep -e ^* | sed -E  s/^\\\\\*\ \(.+\)$/\(\\\\\1\)\ /`'

        	local __git_prompt_dirty=

        	local __prompt_tail="\[\033[35m\]$"
        	local __last_color="\[\033[00m\]"
        	export PS1="$__user_and_host $__cur_location $__git_branch_color$__git_branch$__prompt_tail$__last_color $git_dirty"
        }
        color_my_prompt

        EDITOR=vim

- import_tasks: ../wsl/tasks/minttywsl.yml
