---
- import_tasks: bash.yml
- import_tasks: vim.yml
- import_tasks: tmux.yml

- name: Configure vim as EDITOR
  lineinfile:
    path: /home/alface/.bashrc
    state: present
    line: 'export EDITOR=vim'

