---
- name: install tmux on Arch
  when: ansible_os_family == 'Archlinux'
  pacman:
    name: tmux
  become: yes

- name: install tmux on Debian
  apt:
    pkg: tmux
  when: ansible_os_family == 'Debian'
  become: yes

- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '~/.tmux'
    - '~/.tmux/config'

- name: Configure my ~/.tmux.conf
  copy:
    dest: ~/.tmux/config
    src: "tmux/config/"

- name: Configure my ~/.tmux.conf
  copy:
    dest: ~/.tmux.conf
    src: "tmux/tmux.conf"
